name: talklikeyou
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - cudnn=9
  - ffmpeg
  - pip
  - pip:
      - -r requirements.txt
